export const data = [
  {
    nama: "ADITYA BATISTUTA STIAWAN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✔",
    sidang: "✔",
  },
  {
    nama: "ADRIAN KUSUMA WIDJAJA KARDANA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✔",
    sidang: "✘",
  },
  {
    nama: "AHMAD MUSYADAD HAURY",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "AISYAH HUSNA ALIFAH",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ALYA SAHRANI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ALYA SYIFA FADILAH",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ANDYKA YUANSYAH",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ANISA THERYANA PUTRI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ANNISA AGNI ANNADIYANTI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ATIEK ZAHRATUL 'ULUM",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "CILMA FRESHA PERDANA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "DICKY KURNIA AWALUDIN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "DIFA SAFRINA FADILLA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "DIVA ZAHRAISYA PUTRI UTAMI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "FAKHIRAH AZHAR",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "FARHAN BADRANI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "FIKRI HAIKAL MULYANA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "FITRI FARIDA SOLIHATI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "FREDA DESFITA ARTANTI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "GANESH LINDUNG NUSANTARA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "HENDRA WIJAYA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "INTAN TRI OKTAVIANI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "IRRA PRATIWI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "IVANDIO ZAHRAN BAHY",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "KHOERUNNISA SETIAWATI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "KORNELIUS RHESA VALDIS SETYAWAN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "LAVARANU KEMBANG",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "LUKY SYAWALIDO",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "M. FAHMI RIZAL",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "M. FAHMI ULUMUDIN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MAYANG LESTARI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMAD FAUZAN AL FAYUMI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMAD NURSYAHAL ZEIN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD AHNAF YAFI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD AYYAS",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD FIKRI FAUZAN NAWAWI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD HIJAZ KHOIRULZZABADI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD HILMY TAQI NURANTO",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD MIKAIL ZIYAD",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "MUHAMMAD SOPIAN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "NABILA NUR RAHMITA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "NAJWA ALI SAGITA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "NAJWA ANDIFA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "NAUFAL SHIDQI PURNOMO",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "NIKITA MARSYA DEVANA SIMAMORA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "PINKAN RISMALIKA. PH",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "PUTRI ADE NOVIANTI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "RAISSA DEWI SUKISWADI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "REISA AULIA SODIKIN",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "RESY SUSILAWATI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "RINALDO PARDOMUAN SINAGA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "RINJANI PUTRI DJUNAEDI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "RIRIN NUR AINI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "RISMA YULIA VERONICA MARPAUNG",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SALSABILA PURNAMASARI PUTRI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SHELYA PUTRI NURHALIZA ABDILLAH",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SHIDQI AHMAD BAIHAQI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SITI NABILAH",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SRI LESTARI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SUCI RIZKIAH AZAHRA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "SYIFA AULIA AZZAHRA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "TIARA DEWI IBNATUN SOLIHAT",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "TINO VIENZA WIDIATNA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "VIRGI PERDANA KUSUMA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "VIRLY APRILIAWATI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "WANDA NABILA WENING KATRESNA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "YULIANA SVENTY YASMINE AULHIA SUGIAT",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ZELIKA AMERIA",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
  {
    nama: "ZULFA RAHMANI",
    jalur: "BELUM MENENTUKAN JALUR",
    judul: "BELUM MENENTUKAN JUDUL",
    proposal: "✘",
    sidang: "✘",
  },
];
